<!-- END CONTENT AREA -->
													</div>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
				 
                    </div>

        <div class="clear">
            &nbsp;</div>

    <div id="spi_bottomtxt">
        <span id="ctl00_prop_bottomTxt">
		<table width="100%" class="ms-rteTable-default spifSponsors" cellspacing="0" _moz_resizing="true" style="height: 39px; font-size: 1em"><tbody><tr class="ms-rteTableHeaderRow-default"><th class="ms-rteTableHeaderFirstCol-default" rowspan="1" colspan="4">Våre partnere: </th></tr>
		<tr><td class="ms-rteTableHeaderOddCol-default firstCol" rowspan="1" colspan="1"><a title="Gå til Studentsamskipnaden for Romsdal og Nordmøre" href="http://www.simolde.no/" target="_blank"><span class="logo"></span></a></td>
			<td class="ms-rteTableHeaderOddCol-default secondCol" rowspan="1" colspan="1"><a title="Gå til Molde Campus" href="#" target="_blank"><span class="logo"></span></a></td>
			<td class="ms-rteTableHeaderEvenCol-default thirdCol" rowspan="1" colspan="1"><a title="Gå til Møreforsking Molde" href="http://www.mfm.no/" target="_blank"><span class="logo"></span></a> </td>
			<td class="ms-rteTableHeaderOddCol-default fourthCol" rowspan="1" colspan="1"><a title="Gå til Molde Kunnskapspark" href="http://www.mkp.no/" target="_blank"><span class="logo"></span></a> </td>
		</tr>
		</tbody>
		</table>
		</span>
    </div>

                    </div>				
                </div>
        </div>

    </div>
