	<meta http-equiv="X-UA-Compatible" content="IE=Edge">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta http-equiv="Expires" content="0" />
	<!-- HFN: Not found: link rel="stylesheet" type="text/css" href="http://www.himolde.no/_layouts/1033/EgSpi/Default/EgSpiDefaultLanguageFlags.css"/ -->
	<link rel="stylesheet" type="text/css" href="http://www.himolde.no/_layouts/1044/styles/menu-21.css"/>
	<link rel="stylesheet" type="text/css" href="http://www.himolde.no/Style%20Library/nb-NO/Core%20Styles/page-layouts-21.css"/>
	<link rel="stylesheet" type="text/css" href="http://www.himolde.no/_layouts/1044/styles/Themable/corev4.css"/>
	<link id="ctl00_spi" rel="stylesheet" type="text/css" href="http://www.himolde.no/_layouts/1033/styles/EgSpi/HiM/him.css" />
	<link id="ctl00_spi_inverse" rel="stylesheet" type="text/css" />

    <style type="text/css">
        .s4-skipribbonshortcut { display:none; }
        .ctl00_PlaceHolderMain_emptywebpartzone_0 { border-color:Black;border-width:1px;border-style:Solid; }
        .ctl00_PlaceHolderMain_LeftColumn1_0 { border-color:Black;border-width:1px;border-style:Solid; }
        .ctl00_PlaceHolderMain_CenterColumn1_0 { border-color:Black;border-width:1px;border-style:Solid; }
        .ctl00_PlaceHolderMain_SecondCenterColumn1_0 { border-color:Black;border-width:1px;border-style:Solid; }
        .ctl00_PlaceHolderMain_RightColumn1_0 { border-color:Black;border-width:1px;border-style:Solid; }
        .ctl00_PlaceHolderMain_LeftColumn2_0 { border-color:Black;border-width:1px;border-style:Solid; }
        .ctl00_PlaceHolderMain_CenterColumn2_0 { border-color:Black;border-width:1px;border-style:Solid; }
        .ctl00_PlaceHolderMain_SecondCenterColumn2_0 { border-color:Black;border-width:1px;border-style:Solid; }
        .ctl00_PlaceHolderMain_RightColumn2_0 { border-color:Black;border-width:1px;border-style:Solid; }
        .ctl00_PlaceHolderMain_LeftColumn3_0 { border-color:Black;border-width:1px;border-style:Solid; }
        .ctl00_PlaceHolderMain_CenterColumn3_0 { border-color:Black;border-width:1px;border-style:Solid; }
        .ctl00_PlaceHolderMain_SecondCenterColumn3_0 { border-color:Black;border-width:1px;border-style:Solid; }
        .ctl00_PlaceHolderMain_RightColumn3_0 { border-color:Black;border-width:1px;border-style:Solid; }
        .ctl00_PlaceHolderMain_LeftColumn4_0 { border-color:Black;border-width:1px;border-style:Solid; }
        .ctl00_PlaceHolderMain_CenterColumn4_0 { border-color:Black;border-width:1px;border-style:Solid; }
        .ctl00_PlaceHolderMain_SecondCenterColumn4_0 { border-color:Black;border-width:1px;border-style:Solid; }
        .ctl00_PlaceHolderMain_RightColumn4_0 { border-color:Black;border-width:1px;border-style:Solid; }
        .ctl00_PlaceHolderMain_LeftColumn5_0 { border-color:Black;border-width:1px;border-style:Solid; }
        .ctl00_PlaceHolderMain_CenterColumn5_0 { border-color:Black;border-width:1px;border-style:Solid; }
        .ctl00_PlaceHolderMain_SecondCenterColumn5_0 { border-color:Black;border-width:1px;border-style:Solid; }
        .ctl00_PlaceHolderMain_RightColumn5_0 { border-color:Black;border-width:1px;border-style:Solid; }
        .ctl00_wpz_0 { border-color:Black;border-width:1px;border-style:Solid; }

    </style>
    <style type="text/css">
	/* Overrides by Hans F Nordhaug */
	BODY.SPI_Body {
		overflow: auto !important;
	}
	.multizone_cellLeftZone {
		overflow: visible !important;
	}
	#spi_container {
		min-width: 700px;
	}
	#s4-workspaceInnerWrapper, #s4-bodyContainer  {
		min-width: 700px !important;
	}
	#ctl00_MSO_ContentDiv_SPI div.welcome {
		padding: 10px 20px !important;
	}
	.spi_topborder, .spiGlobalNav {
		min-width: 944px !important;
	}
	.spiGlobalNav {
		overflow: hidden !important;
	}
	#s4-bodyContainer {
		// overflow: auto !important; 
	}
	#spi_breadcrumbs { border-top: 0px !important; }
	#spi_bottomtxt table.spifSponsors td .logo { width: 171px !important; }
    </style>
</head>
<!-- Body -->
<body scroll="no" class="SPI_Body">

    <div class="noindex">
        <span class="s4-notdlg"><a id="A2" href="#mainContent" class="ms-SkiptoMainContent" accesskey="X">Hopp til hovedinnhold</a> </span>
        <!--  End -->
    </div>


    <div id="spi_container">
        <div id="spi_container_inner">
            <div id="spi_content">
                <div id="s4-workspace" class="s4-nosetwidth">
                <div id="s4-workspaceInnerWrapper">

                <div class="spi_topborder s4-notdlg noindex">
                    <!-- Start header -->
                    <div id="spi_header">
                        <div id="spi_header_inner">
                            <!-- Start logo -->
                            <div id="spi_logo" class="noindex">
                                <span id="ctl00_prop_logo"><a title="Logo" href="http://www.himolde.no"><img title="Logo" src="http://www.himolde.no/PublishingImages/logo.png" alt="Logo" style="border-width:0px;" /></a></span>
                            </div>
                            <!-- End logo -->
                            <!-- Update Task No:3699 25/08/11 -->
                            <div id="spi_topnav">
                                <!-- Update Task No:3699 25/08/11 -->
                                <ul class="topLinkList">
                                </ul>
                            </div>
                        </div>
                    </div>
                    <!--End header-->
                </div>
                <div class="s4-notdlg spiGlobalNav">
                    <a name="startNavigation"></a>
                    <!-- Jump to Navigation [ US #2672, Update, 25-08-11, Sprint 23 ]-->

                        <div id="menuHolder" class="noindex">

                            <div id="zz1_TopNavigationMenuV4" class="spi_mainmenu_1">
                                                                <div class="menu horizontal menu-horizontal">
                                                                        <ul class="root static">
                                                                        </ul>
                                                                </div>
                                                        </div>


                            <div id="spi_search" class="noindex">
                                <a name="searchContent"></a>
                            </div>
                        </div>
                        <!-- id="menuHolder" -->

                </div>

					<div id="s4-bodyContainer">
                        <div id="s4-titlerow" class="s4-pr s4-notdlg s4-titlerowhidetitle">
                            <div id="spi_breadcrumbs"><a href="http://www.himolde.no/">HiMolde</a> &gt; <a href='http://kvalitet.himolde.no/'>Kvalitetssystem</a> </div>
                        </div>
                        <!--Begin Nav|Content Area-->

                                        <div id="s4-mainarea" class="spi_pr spi_widecontentarea">
                                                <!-- The MSO_ContentTable div must surround the content area. The id attribute is required. -->
                                                <div class="spi_ca s4-ca-dlgNoRibbon" id="MSO_ContentTable" style="margin-left: 4px;">
                                                        <div class="spi-ba">
                                                                <div class="spi-bodyareacell">
                                                                        <div id="ctl00_MSO_ContentDiv_SPI">
                                                                                <a name="mainContent"></a>
                                                                                <!-- Jump to maincontent -->



                                                                                <div class="welcome blank-wp">
                                                                                        <div id="ctl00_PlaceHolderMain_page_container">
                                                                                                <div id="containerDiv" class="multizone_container">
                                                                                                        <div class="multizone_row" id="row1">
<!-- START CONTENT AREA -->
